name: Deploy React Frontend via FTP

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build React
        run: npm run build

      - name: Clean server directory and Deploy
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: build/
          server-dir: /
          dangerous-clean-slate: true

      - name: Run chown and chmod over SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: 22
          script: |
            echo "${{ secrets.SSH_PASSWORD }}" | sudo -S chown -R qualite:qualite /var/www/html
            echo "${{ secrets.SSH_PASSWORD }}" | sudo -S chmod -R 755 /var/www/html
